### PR TITLE
Fix: response with format "uuid" or "guid"

### LINKED ISSUE #32: uuid response type as string and not converted to Guid
Return type with payload of type System.Guid is created, but the client tries to create the return type with the string content directly instead of creating a System.Guid first.

Example:
- specification.json
``` json
{   "paths": { "/auth/repo/": { "post": {
   "operationId": "PostAuthRepo",
   "responses": { "201": { "content": { "application/json" : { "schema": {
      "type": "string",
      "format": "uuid" }}}}}}}}}
```
- Types.fs
``` fsharp
[<RequireQualifiedAccess>]
type PostAuthRepo =
    | Created of payload: System.Guid
    | Unauthorized
    | Forbidden
```
- Client.fs
``` fsharp
member this.PostAuthRepo(repository: string, body: Authorization) =
        async {
            let requestParts =
                [ RequestPart.path ("repository", repository)
                  RequestPart.jsonContent body ]

            let! (status, content) =
                OpenApiHttp.postAsync url "/authorization/repositories/{repository}" headers requestParts

            if status = 201 then
                return PostAuthorizationRepository.Created content
            else if status = 401 then
                return PostAuthorizationRepository.Unauthorized
            else
                return PostAuthorizationRepository.Forbidden
        }
```
```return PostAuthorizationRepository.Created content``` gives an error and should be ```return PostAuthorizationRepository.Created (System.Guid content)```

### PR DESCRIPTION
**Pull request by MichaelMay81**
Fixes #32

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi @MichaelMay81 although this change would allow Hawaii to generate code that compiles, I don't think it will work at runtime. This is because the `content` is a JSON string and not just a string. JSON strings looks like this (quoted):
```json
"\"e204918b-a525-4a18-98bf-cf389c8184d3\""
```
Which fails when you directly call
```fs
System.Guid "\"e204918b-a525-4a18-98bf-cf389c8184d3\""
```
Instead of directly using `System.Guid`, you should use `Serializer.deserialize`like the other parts do

**Comment by MichaelMay81** [comment]
Mea culpa. Fix pushed.

**Comment by Zaid-Ajaj** [comment]
Done! merged and published as of v0.58 🚀 can you it a try?

**Comment by MichaelMay81** [comment]
seems to work.
"hawaii --version" is a bit out of date :)

**Comment by Zaid-Ajaj** [comment]
oh yeah my bad! I will update maybe when #31 is resolved? 😉

**Pull request merged**
