### PR TITLE
Add support for unlimited number of response status codes

### PR DESCRIPTION
**Pull request by vschep**
I would like to add support for an unlimited number of response status codes. Before that only a maximum of 6 status codes are distinguished.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hi @vschep this looks very promising! Can you please run `dotnet run generate-and-build` inside the `./build` directory and commit the results to the PR? this is so that we can see how the end result looks like before merging 😄

**Comment by vschep** [comment]
Hi @Zaid-Ajaj, yes, sure, that is a great idea 😄  I have run ```dotnet run generate-and-build``` and committed the results to the PR.

**Comment by vschep** [comment]
Running ```dotnet run -- integration``` produces errors at my branch and at the master branch, see below. When I change the target framework of ControlApiV1.fsproj from netstandard2.0 to net7.0 the 'UnprocessableEntity' disappears. As far as I understand UnprocessableEntity has been added only lately to the .NET SDK. But the 'ruleresponse' error stays.

What do you @Zaid-Ajaj think how we should deal with it?

### Error log for branch unlimited-responses


```
dotnet --version
7.0.400

dotnet run -- integration
```

```
Attempting to generate project ControlApiV1 from https://api.apis.guru/v2/specs/ably.net/control/1.0.14/openapi.json
Succesfully generated project /Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj
MSBuild version 17.7.1+971bf70db for .NET
  Determining projects to restore...
  Restored /Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj (in 63 ms).
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Types.fs(3196,27): error FS0039: The type 'ruleresponse' is not defined. Maybe you want one of the following:   iftttruleresponse   rulesource   appresponse   rulesourcepatch   queueresponse [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Types.fs(3196,27): error FS0039: The type 'ruleresponse' is not defined. Maybe you want one of the following:   iftttruleresponse   rulesource   appresponse   rulesourcepatch   queueresponse [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(56,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(100,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(135,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(205,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(322,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(396,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(469,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(488,30): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]

Build FAILED.
```

### Error log for branch master

```
dotnet --version
7.0.400

dotnet run -- integration
```

```
Succesfully generated project /Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj
MSBuild version 17.7.1+971bf70db for .NET
  Determining projects to restore...
  Restored /Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj (in 64 ms).
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Types.fs(3196,27): error FS0039: The type 'ruleresponse' is not defined. Maybe you want one of the following:   iftttruleresponse   rulesource   appresponse   rulesourcepatch   queueresponse [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Types.fs(3196,27): error FS0039: The type 'ruleresponse' is not defined. Maybe you want one of the following:   iftttruleresponse   rulesource   appresponse   rulesourcepatch   queueresponse [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(60,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(111,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(148,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(224,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(350,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(432,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(511,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]
/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/Client.fs(533,45): error FS0039: The type 'HttpStatusCode' does not define the field, constructor or member 'UnprocessableEntity'. [/Users/viktor/src/vschep_github/Hawaii/examples/ControlApiV1/ControlApiV1.fsproj]

Build FAILED.
```

**Comment by Zaid-Ajaj** [comment]
The resulting code looks great @vschep 🙏 

> What do you @Zaid-Ajaj think how we should deal with it?

I think we can filter it out from the list of available responses. I would love to stay at `netstandard2.0` because it is compatible with everything (Fable, latest dotnet and even .NET Framework v4.6.1)

**Comment by vschep** [comment]
Thanks @Zaid-Ajaj ! 
I am not sure if I understand it correctly. Do you mean to filter out UnprocessableEntity? This is a response that we need indeed.

**Comment by Zaid-Ajaj** [comment]
> I am not sure if I understand it correctly

Forget about my suggestion, it is not a good idea to remove responses based on the target framework 😓

How about the following, instead of 
```fs
match status with
| HttpStatusCode.OK -> return PlaceOrder.OK(Serializer.deserialize content)
| _ -> return PlaceOrder.MethodNotAllowed
```
we generate:
```fs
match int status with
| 200 -> return PlaceOrder.OK(Serializer.deserialize content)
| _ -> return PlaceOrder.MethodNotAllowed
```
This way, we don't have to reference `UnprocessableEntity` statically in the code

**Comment by vschep** [comment]
That sounds good 😃 . Then Hawaii would be independent of the target framework. And the status code as a number is as well known as the status code name. So the generated code should still look good.

**Comment by vschep** [comment]
Shall I adapt the code accordingly?

**Comment by Zaid-Ajaj** [comment]
Yes please 🙏

**Comment by vschep** [comment]
@Zaid-Ajaj Please check my last commit which contains the proposed change.

**Comment by Zaid-Ajaj** [comment]
The changes look great! For Fable clients calling `int` on `status` is redundant because `status` is already an integer there but that is not a blocker to get this merged in 🎉

**Comment by Zaid-Ajaj** [comment]
Merged and published as of v0.67 🚀 thanks a lot @vschep 🙏

**Comment by vschep** [comment]
Great thanks for providing us the awesome Hawaii tool @Zaid-Ajaj  😃

**Pull request merged**
